In [1]:
import numpy as np

In [5]:
#1- Create a NumPy program to create a 3x3 identity matrix
identityMatrix = np.eye(3)
print ("3x3 Identity Matrix:")
print(identityMatrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
#2- Create a NumPy program to generate 5 random number between 0 and 1
randomMatrix = np.random.rand(5)
print ("5 random number between 0 and 1:")
print(randomMatrix)

5 random number between 0 and 1:
[0.89670223 0.27150385 0.68637515 0.92862268 0.27518985]


In [8]:
"""3- Write a NumPy program to append values to the end of an array.
	Expected Output:
	Original array:
	[10, 20, 30]
	After append values to the end of the array:
	[10 20 30 40 50 60 70 80 90]
"""
original_array = np.array([10, 20, 30])
append_array = np.array([40, 50, 60, 70, 80, 90])
new_array = np.append(original_array, append_array)

print("Original array:")
print(original_array)
print("After append values to the end of the array:")
print(new_array)


Original array:
[10 20 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]
