In [ ]:
!pip3 install scipy==1.1.0

In [ ]:
pip install --upgrade pip setuptools wheel


In [ ]:
pip install imageio pillow


In [2]:
import numpy as np

np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [7]:
np.array([4, 3, 0]) + np.array([0, 2, 2])

array([4, 5, 2])

In [ ]:
#from scipy.misc import imread, imsave, imresize

In [ ]:
#alternate imports of scipy
from skimage.transform import resize
from imageio import imwrite #imsave
from cv2 import imread ,resize
from PIL import Image
import numpy as np


In [ ]:
import imageio
from PIL import Image
import numpy as np

# Read an image
image = imageio.imread('/content/right.jpeg')

print('Image type: {}'.format(type(image)))
print('Image shape: {}'.format(image.shape))

# Resize an image using Pillow
image_pil = Image.fromarray(image)
resized_image_pil = image_pil.resize((480, 228))

# Convert the resized PIL image back to a NumPy array
resized_image = np.array(resized_image_pil)

print('Resized image shape: {}'.format(resized_image.shape))

# Save the resized image using imageio
imageio.imwrite('/content/right2.jpeg', resized_image)


Image type: <class 'numpy.ndarray'>
Image shape: (248, 465, 3)
Resized image shape: (228, 480, 3)


<ipython-input-3-a9fb6eefa7c8>:6: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  image = imageio.imread('/content/right.jpeg')


In [ ]:
# RGB = [1.0 , 0.9 , 0.8]
colored_img =image*[1.0, 0.9, 0.8]
print(colored_img.dtype, colored_img.shape)
c_img = colored_img.astype(np.uint8)
print(c_img.dtype , c_img.shape)
imwrite('/content/SpaceMan_colored.jpg' , c_img)

float64 (1280, 853, 3)
uint8 (1280, 853, 3)


In [ ]:
import tensorflow as tf

# Define the constants and operations
x = tf.constant(2)
y = tf.constant(3)

add_op = tf.add(x, y, name='add')
mult_op = tf.multiply(x, y, name='multiply')
pow_op = tf.pow(add_op, mult_op, name='power')
res = tf.multiply(x, pow_op, name='Useless')

# Execute the operations
pout = pow_op.numpy()
res_out = res.numpy()

print(pout)
print(res_out)

# Using TensorFlow 2.x to compute the segment sum
c = tf.constant([[1, 2, 3, 4], [-1, -2, -3, -4], [5, 6, 7, 8]])
a = tf.math.segment_sum(c, tf.constant([0, 0, 1]))
print(a.numpy())

# Using TensorFlow 2.x to compute the unsorted segment sum
a_unsorted = tf.math.unsorted_segment_sum(c, tf.constant([0, 1, 0]), num_segments=2)
print(a_unsorted.numpy())


15625
31250
[[0 0 0 0]
 [5 6 7 8]]
[[ 6  8 10 12]
 [-1 -2 -3 -4]]


In [ ]:
from keras.datasets import mnist, fashion_mnist
from keras.models import Sequential, load_model
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from keras.utils import to_categorical
from keras.preprocessing.image import load_img, img_to_array
import keras.backend as k

# Hyperparameters
batch_size = 128
num_classes = 10
epochs = 12
img_rows, img_cols = 28, 28

# Load and preprocess MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()
if k.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32') / 255
x_test = x_test.astype('float32') / 255
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

# Build the model
model = Sequential([
    Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=input_shape),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(pool_size=(2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])
model.summary()

# Compile and train the model
model.compile(loss='categorical_crossentropy', optimizer='Adadelta', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, validation_data=(x_test, y_test))

# Evaluate the model
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss=', score[0])
print('Test accuracy=', score[1])

# Save the model
model.save("model.h5")
print("Model saved")

# Function to load and prepare an image
def load_image(filename):
    img = load_img(filename, color_mode='grayscale', target_size=(28, 28))
    img = img_to_array(img)
    img = img.reshape(1, 28, 28, 1)
    img = img.astype('float32') / 255.0
    return img

# Function to load an image and predict its class
def run_example():
    img = load_image('sample_image.png')
    model = load_model('model.h5')
    result = model.predict_classes(img)
    print(result[0])

# Run the example
run_example()

# Fashion MNIST model definition and training
def load_fashion_mnist():
    (trainX, trainY), (testX, testY) = fashion_mnist.load_data()
    trainX = trainX.reshape((trainX.shape[0], 28, 28, 1))
    testX = testX.reshape((testX.shape[0], 28, 28, 1))
    trainY = to_categorical(trainY)
    testY = to_categorical(testY)
    return trainX, trainY, testX, testY

def prep_pixels(train, test):
    train = train.astype('float32') / 255.0
    test = test.astype('float32') / 255.0
    return train, test

def define_model():
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform', input_shape=(28, 28, 1)),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(100, activation='relu', kernel_initializer='he_uniform'),
        Dense(10, activation='softmax')
    ])
    opt = keras.optimizers.SGD(lr=0.01, momentum=0.9)
    model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

def run_test_harness():
    trainX, trainY, testX, testY = load_fashion_mnist()
    trainX, testX = prep_pixels(trainX, testX)
    model = define_model()
    model.fit(trainX, trainY, epochs=10, batch_size=32, verbose=1)
    model.save("fashion_model.h5")
    print("Fashion model saved")

# Run the test harness for Fashion MNIST
run_test_harness()
